# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/animations:enabled = 0
animations:enabled = 1
debug:enable_stdout_logs = 0
decoration:blur:enabled = 1
