# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
input {
    kb_layout  = us , ir
    kb_model   = 
    kb_variant = 
    kb_options = caps:escape ,grp:toggle
    kb_rules   =

    repeat_delay = 250
    repeat_rate = 35

    follow_mouse = 1
    special_fallthrough = true
    off_window_axis_events = 2

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.7
    }
}

gesture = 4, swipe, move,
gesture = 3, up, dispatcher, global, quickshell:overviewWorkspacesToggle
gesture = 3, down, dispatcher, global, quickshell:overviewWorkspacesClose
gesture = 3, horizontal, workspace
gesture = 3, pinch, float
