# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# ######## Workspace rules ########
# special workspace with floating terminal
workspace = special:special, gapsout:30

windowrule = match:class ^(floatterm)$, float on, center on
workspace = special:floatterm, on-created-empty:[floating] alacritty --class floatterm

windowrule = match:class ^(aichat)$, float on, center on
workspace = special:aichat, on-created-empty:[floating] zen-browser --new-window 'https://gemini.google.com/u/0'

