vim.g.base46_cache = vim.fn.stdpath "data" .. "/base46/"
vim.g.mapleader = " "

-- bootstrap lazy and all plugins
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"

if not vim.uv.fs_stat(lazypath) then
  local repo = "https://github.com/folke/lazy.nvim.git"
  vim.fn.system { "git", "clone", "--filter=blob:none", repo, "--branch=stable", lazypath }
end

vim.opt.rtp:prepend(lazypath)

local lazy_config = require "configs.lazy"

-- load plugins
require("lazy").setup({
  {
    "NvChad/NvChad",
    lazy = false,
    branch = "v2.5",
    import = "nvchad.plugins",
  },

  { import = "plugins" },
}, lazy_config)

-- load theme
dofile(vim.g.base46_cache .. "defaults")
dofile(vim.g.base46_cache .. "statusline")

require "options"
require "nvchad.autocmds"

vim.schedule(function()
  require "mappings"
end)

-- generated by gpt
vim.api.nvim_create_user_command("DapGenerateRustConfig", function()
  local cargo_toml = "Cargo.toml"
  if vim.fn.filereadable(cargo_toml) == 0 then
    print("No Cargo.toml found in current directory!")
    return
  end

  local lines = vim.fn.readfile(cargo_toml)
  local bins = {}    -- Store binaries defined in Cargo.toml
  local package_name -- Fallback: package name from the [package] section
  local in_package_section = false
  local in_bin_section = false

  for _, line in ipairs(lines) do
    line = line:match("^%s*(.-)%s*$") -- trim spaces

    if line == "[package]" then
      in_package_section = true
    elseif line:match("^%[") then
      in_package_section = false
    end

    if in_package_section and not package_name then
      local name = line:match('^name%s*=%s*"(.-)"')
      if name then
        package_name = name
      end
    end

    if line == "[[bin]]" then
      in_bin_section = true
    elseif line:match("^%[") and line ~= "[[bin]]" then
      in_bin_section = false
    end

    if in_bin_section then
      local name = line:match('^name%s*=%s*"(.-)"')
      if name then
        table.insert(bins, name)
      end
    end
  end

  -- If no explicit binary is defined, use the package name (if available)
  if #bins == 0 and package_name then
    table.insert(bins, package_name)
  end

  if #bins == 0 then
    print("No binary found in Cargo.toml!")
    return
  end

  -- Use a multiline string template for the dap configuration
  local header = [[
local dap = require("dap")

dap.adapters.codelldb = {
  type = "server",
  port = "${port}",
  executable = {
    command = "/home/ark/.local/share/nvim/mason/bin/codelldb",     -- adjust as needed, must be absolute path
    args = { "--port", "${port}" },
  },
}

dap.configurations.rust = {
]]

  local footer = "\n}\n"

  -- Build configuration entries for each binary using a template
  local entry_template = [[
  {
    name = "%s",
    type = "codelldb",
    request = "launch",
    program = function()
      return vim.fn.getcwd() .. "/target/debug/%s"
    end,
    cwd = "${workspaceFolder}",
    stopOnEntry = false,
  },]]

  local entries = {}
  for _, bin in ipairs(bins) do
    table.insert(entries, string.format(entry_template, bin, bin))
  end

  local output = header .. table.concat(entries, "\n") .. footer

  local output_file = ".nvim/dap.lua"
  if vim.fn.isdirectory(".nvim") == 0 then
    vim.fn.mkdir(".nvim", "p")
  end
  vim.fn.writefile(vim.split(output, "\n"), output_file)
  print(string.format("Generated %s with %d configuration(s).", output_file, #bins))
end, { desc = "Generate nvim-dap.lua configuration for Rust projects" })
