# HDMI port: mirror display. To see device name, use `hyprctl monitors`
# monitor=HDMI-A-1,1920x1080@60,1920x0,1,mirror,eDP-1

# MONITOR CONFIG
monitor=,preferred,auto,auto
monitor= eDP-1,preferred,auto,1

########## BDONY SDSU lab ##########
### long oled
# # SDSU-lab long OLED
# monitor= HDMI-A-1, preferred, auto-up, 1

### samsung oled left
# # SDSU-lab short OLED Acer
# monitor=DP-6,2560x1440@60,0x0,1
#
# # SDSU-lab rotated samsung
# monitor=DP-7,2560x1440@60,-1440x-1280,1,transform,1
#
# # Laptop (below DP-6)
# monitor=eDP-1,1920x1200@60,-1920x1280,1

### samsung oled right
# SDSU-lab short OLED Acer
#  ___________0_______________
# |             +-------+
# |             |       |
# | +----------+|       |
# | |          ||       |
# | | Acer-OLD ||  SAM  |
# | |          || SUNG  |
# 0 +----------+|       |
# |     +------+|       |
# |     | eDP-1|+-------+
# |     +------+
# seen both descs don't know why!
monitor=desc: Acer Technologies XZ322QU V3 2513228553W01,2560x1440@60,-2560x-1440,1
monitor=desc: Navatek Engineering Corporation NOVATEK,2560x1440@60,-2560x-1440,1

# SDSU-lab rotated samsung
monitor=desc: Samsung Electric Company LS27A800U HCRY300603,2560x1440@60,0x-1965,1,transform,3
# manualy disable the duplicate samsung monitor 
## might need to change after each plug/unplug since the number changes
monitor=DP-9,disable
monitor=DP-6,disable

monitor=eDP-1,1920x1200@60,-1920x0,1

workspace = 1, monitor:DP-5, default:true
workspace = 2, monitor:DP-5
workspace = 3, monitor:DP-5
workspace = 4, monitor:DP-5
workspace = 5, monitor:DP-5
workspace = 6, monitor:DP-5
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-7
workspace = 9, monitor:eDP-1
workspace = 0, monitor:eDP-1


