return {
  require "plugins.neotest",
  require "plugins.dap",
  require "plugins.nvim-dap-projects",
  require "plugins.crates",
  require "plugins.rustacean",
  require "plugins.gitsigns",
  require "plugins.mason",
  require "plugins.nvim-treesitter",
  require "plugins.nvim-tree-sitter-context",
  -- require "plugins.nvim-tree-sitter-playground",
  require "plugins.conform",
  require "plugins.lspconfig",
  require "plugins.telescope",
  require "plugins.markdown",
  require "plugins.cmp",
  require "plugins.avante",
  require "plugins.copilot",
  require "plugins.copilot-cmp"
}
